### ISSUE TITLE
Извлечь методы, вынести переменные

### ISSUE THREAD

**Issue by moetelo** [seele402/Heute#12]
Хорошо, есть у нас:
https://github.com/JigiDo/Heute/blob/0f324bc8e2dce116af28da040c525852cded2920/Heute/MainWindow.xaml.cs#L82
 
Но внутри этого цикла каждый раз происходит:
1. https://github.com/JigiDo/Heute/blob/0f324bc8e2dce116af28da040c525852cded2920/Heute/MainWindow.xaml.cs#L88
2. https://github.com/JigiDo/Heute/blob/0f324bc8e2dce116af28da040c525852cded2920/Heute/MainWindow.xaml.cs#L90
 
То есть, while(true) создаётся новый VkApi. Создаётся так быстро, как позволяет процессор. И авторизуется тоже настолько же быстро. **Зачем?** Один раз авторизовались и всё. Дальше используем авторизованный экземпляр.
Нужно вынести из цикла. Может, вообще вынести из метода `Ellipse_MouseLeftButtonDown` в проперти класса. Может, создать отдельный класс для работы с датой, временем и ВК Апи, чтобы удовлетворить #7.
 
Также, эти две строки повторяются и в `Ellipse_MouseLeftButtonDown`, и в `Back_MouseLeftButtonDown`. Эту проблему как раз решит рефакторинг в рамках этой задачи, так как эти строки будут вынесены в отдельное место, и в этих методах останется лишь одно:
```csharp 
api.Messages.Send(new VkNet.Model.RequestParams.MessagesSendParams 
```
Что уже само по себе адекватно выглядит.

**Comment by moetelo** [comment]
@JigiDo Чем тебе не нравится?

**Comment by moetelo** [comment]
@veselv2010 
Думаешь, на каждый клик имеет создавать новый экземпляр VkApi?
Кажется, логичнее создать его единожды -- в момент авторизации. Когда получен токен.

**Comment by moetelo** [comment]
Issue не решена, но если не хочется решать, то просто открой, пусть висит хотя бы.

**Comment by seele402** [comment]
@Shifu462
Есть такое, я тоже изначально хотел вынести за пределы свитча.

**Comment by seele402** [comment]
Да там решать-то, сейчас сделаю.

**Comment by moetelo** [comment]
Ты проверял, что написал?

**Comment by seele402** [comment]
Пока нет, фикс #15 код поломал каким-то образом, как разберемся - проверю.

**Comment by seele402** [comment]
Не работает
