### ISSUE TITLE
Обозначать в окне программы успешность выполнения задачи

### ISSUE THREAD

**Issue by veselv2010** [seele402/Heute#8]
Если это отправка сообщения - выводить надпись об успешно отправленном сообщении
и т. д.

**Comment by seele402** [comment]
На самом деле не столь значимый функционал, но, думаю, можно сделать индикацию того, что цикл начался и ожидает заданного времени (хотя, по сути, сам свич это показывает), а по окончанию оного - соответствующее уведомление.
